# Generated by Django 4.1.4 on 2023-03-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
    ]
